package io.github.yajuhua.invidious.wrapper.pojo.dto;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * /api/v1/channels/ID
 */
@NoArgsConstructor
@Data
public class ChannelDTO {

    @SerializedName("author")
    private String author;
    @SerializedName("authorId")
    private String authorId;
    @SerializedName("authorUrl")
    private String authorUrl;
    @SerializedName("authorBanners")
    private List<AuthorBannersDTO> authorBanners;
    @SerializedName("authorThumbnails")
    private List<AuthorThumbnailsDTO> authorThumbnails;
    @SerializedName("subCount")
    private Integer subCount;
    @SerializedName("totalViews")
    private Integer totalViews;
    @SerializedName("joined")
    private Integer joined;
    @SerializedName("autoGenerated")
    private Boolean autoGenerated;
    @SerializedName("isFamilyFriendly")
    private Boolean isFamilyFriendly;
    @SerializedName("description")
    private String description;
    @SerializedName("descriptionHtml")
    private String descriptionHtml;
    @SerializedName("allowedRegions")
    private List<String> allowedRegions;
    @SerializedName("tabs")
    private List<String> tabs;
    @SerializedName("tags")
    private List<String> tags;
    @SerializedName("authorVerified")
    private Boolean authorVerified;
    @SerializedName("latestVideos")
    private List<?> latestVideos;
    @SerializedName("relatedChannels")
    private List<?> relatedChannels;

    @NoArgsConstructor
    @Data
    public static class AuthorBannersDTO {
        @SerializedName("url")
        private String url;
        @SerializedName("width")
        private Integer width;
        @SerializedName("height")
        private Integer height;
    }

    @NoArgsConstructor
    @Data
    public static class AuthorThumbnailsDTO {
        @SerializedName("url")
        private String url;
        @SerializedName("width")
        private Integer width;
        @SerializedName("height")
        private Integer height;
    }
}
