package io.github.yajuhua.invidious.wrapper.pojo.dto;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@NoArgsConstructor
@Data
public class SearchDTO {

    @SerializedName("type")
    private String type;
    @SerializedName("author")
    private String author;
    @SerializedName("authorId")
    private String authorId;
    @SerializedName("authorUrl")
    private String authorUrl;
    @SerializedName("authorVerified")
    private Boolean authorVerified;
    @SerializedName("authorThumbnails")
    private List<AuthorThumbnailsDTO> authorThumbnails;
    @SerializedName("autoGenerated")
    private Boolean autoGenerated;
    @SerializedName("subCount")
    private Integer subCount;
    @SerializedName("videoCount")
    private Integer videoCount;
    @SerializedName("channelHandle")
    private String channelHandle;
    @SerializedName("description")
    private String description;
    @SerializedName("descriptionHtml")
    private String descriptionHtml;

    @NoArgsConstructor
    @Data
    public static class AuthorThumbnailsDTO {
        @SerializedName("url")
        private String url;
        @SerializedName("width")
        private Integer width;
        @SerializedName("height")
        private Integer height;
    }
}
