name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        run: mvn --version

      - name: Run tests
        run: |
            mvn test
